### ISSUE TITLE
Includining https://zenodo.org/records/4587338?

### ISSUE THREAD

**Issue by Rafnuss** [enram/aloftdata.eu#14]
Hi,
Great to see this plateform taking shape! I was just wandering if you think it would make sense to also include the 2018 dataset we cleaned for 37 weather radars? https://zenodo.org/records/4587338. 
Cheers,

**Comment by peterdesmet** [comment]
Nice! That dataset is in a different format than the hdf5/csv datasets currently in the aloft repository, so I wouldn't copy it there.

Rather, we are planning to make a (metadata) registry with aeroecology-relevant datasets and software that are out there. They can be in whatever format, as long as the dataset metadata is the same. Our plan is to use Zenodo for this, so your dataset is a good test case. **Would you be willing to add your dataset (and maybe other relevant Zenodo deposits) to the [aloft community](https://zenodo.org/communities/aloft)**

<img width="368" alt="Screenshot 2024-08-27 at 18 02 53" src="https://github.com/user-attachments/assets/4ea28ec9-ae44-40f3-ba3c-f802f90e5220">


1. On your deposit page, see right sidebar with communities
2. Click cogwheel to `Submit to community`
3. Search for `aloft`
4. `Select`



Not much will happen with that right now, but your dataset will automatically be on our radar (pun intended) when we create the registry.

**Comment by Rafnuss** [comment]
Ok, great, thanks for the suggestion. I've just sumbitted the request! Thanks!
