### ISSUE TITLE
OPERA DB json contains empty property

### ISSUE THREAD

**Issue by peterdesmet** [enram/aloftdata.eu#9]
The opera DB json now contains an empty property for each radar, that was not there before:

```json
{
        "number": "1209",
        "country": "Austria",
        "countryid": "LOWM41",
        "oldcountryid": "OS41",
        "wmocode": "11038",
        "wigosid": "",
        "odimcode": "atrau",
        "location": "Wien/Schwechat",
        "status": "1",
        "latitude": "48.074",
        "longitude": "16.536",
        "heightofstation": "",
        "band": "C",
        "doppler": "Y",
        "polarization": "D",
        "maxrange": "224",
        "startyear": "1978",
        "heightantenna": "224",
        "diametrantenna": "",
        "beam": "0.88",
        "gain": "45.5",
        "frequency": "5.625",
        "stratus": "",
        "cirusnimbus": "",
        "wrwp": "",
        "": "" <----
    },
```

@BarVodSur can this be removed?

**Comment by BarVodSur** [comment]
It is removed.

**Comment by BarVodSur** [comment]
Dear Peter,

Excuse me for late respond. Yes, it’s possible to remove the last raw. We will to do it on next update. 

 

BR,

Barbara 

 

------------------------------------------------------------------------------------------------

Barbara Vodarić Šurija, mag.phys & geophys. 

Meteorological and Hydrological Service of Croatia (DHMZ)

Remote Sensing Department

Data Analysis and Remote Sensing Improvement Division

Ravnice 48, 10000 Zagreb, Croatia

mob: +385995356466

e-mail: ***@***.*** ***@***.***> 

 

 

 

From: Peter Desmet ***@***.***> 
Sent: Friday, September 9, 2022 9:20 PM
To: enram/aloftdata.eu ***@***.***>
Cc: Barbara Vodaric Surija ***@***.***>; Assign ***@***.***>
Subject: [enram/aloftdata.eu] OPERA DB json contains empty property (#9)

 

The opera DB json now contains an empty property for each radar, that was not there before:

{
        "number": "1209",
        "country": "Austria",
        "countryid": "LOWM41",
        "oldcountryid": "OS41",
        "wmocode": "11038",
        "wigosid": "",
        "odimcode": "atrau",
        "location": "Wien/Schwechat",
        "status": "1",
        "latitude": "48.074",
        "longitude": "16.536",
        "heightofstation": "",
        "band": "C",
        "doppler": "Y",
        "polarization": "D",
        "maxrange": "224",
        "startyear": "1978",
        "heightantenna": "224",
        "diametrantenna": "",
        "beam": "0.88",
        "gain": "45.5",
        "frequency": "5.625",
        "stratus": "",
        "cirusnimbus": "",
        "wrwp": "",
        "": "" <----
    },

@BarVodSur <https://github.com/BarVodSur>  can this be removed?

**Comment by peterdesmet** [comment]
Great, can you let me know when it is done, so I can update and close this issue?

**Comment by BarVodSur** [comment]
Yes! I will put a reminder. 

 

BR,

Barbara

**Comment by BarVodSur** [comment]
Dear Peter.

 

From last update last week empty row is removed.

 

BR,

Barbara
